### ISSUE TITLE
Fast, platform-specific Hamster implementations needed

### ISSUE THREAD

**Issue by alexdowad** [hamstergem/hamster#126]
As demonstrated by Clojure, persistent data structures are powerful and generally applicable enough to base a whole style of programming on. Ruby programmers have yet to benefit from assimilating that style and its strengths. Although `Hamster` has existed for about 4 years, and has attracted some attention (note the number of GH stars), it appears that it is still hardly used "in the wild".

To make persistent structures viable for large-scale adoption by Ruby programmers, performance is one barrier which has yet to be overcome. `Hamster` is fast enough for a lot of applications, but not fast enough that a new adopter can use it confidently without even worrying about performance.

Actually, persistent data structures even have the potential to out-perform more traditional, mutable data structures in some read-heavy applications. But `Hamster` is just not there yet.

The level of performance I am talking about here is not attainable in pure, portable Ruby. It is necessary to go closer to the underlying platform. I would like to see one "tuned" implementation of `Hamster` for each popular Ruby.

Users who install the `hamster` gem should automatically get the version which is tuned specifically to their Ruby interpreter. Those who specifically want the pure-Ruby "reference" Hamster can get it as `hamster-ruby` or something like that. This means that the various Hamster implementations will all have to match gem version numbers. In other words, the latest 1.0-series release of Hamster in C (for MRI), Hamster in Java (for JRuby), and pure-Ruby Hamster should all provide identical public APIs. Likewise for the latest 1.1-series releases, 1.2-series, and so on.

It may be that the current, pure-Ruby version will not be used much after that. But it is still valuable and should be kept around (and kept up-to-date). It can serve as a "reference implementation", useful for people who want to build a new "tuned" implementation, easily hackable by people who want to experiment with API changes, and readable for people who just want to peek inside and see what is there.

We should aim for 100%, "drop-in replacement" API compatibility between Hamsters, as long as client programmers stick to using the public API and not monkey-patching anything or calling private methods. As soon as people do those things, all bets are off (and the documentation will make that clear).

In some cases, the pursuit of speed may lead us to adjust the behavior of Hamster collections in obscure corner cases. For example, it might be discovered that by changing some obscure, minor aspect of the public API, a significant speed boost can be achieved in the Java version. That is fine, _but_ the other versions (even pure-Ruby) should also be tweaked to stay compatible.

All the Hamsters can share the same test suite. To facilitate that, it might be necessary to pull the test suite out into a gem of its own, and make it a development dependency. The version numbers should match Hamster itself.

Disclosure: I already have part of a C implementation working, and part of one in Java as well.

**Comment by dzjuck** [comment]
Should we at first add JRuby and Rubinius support to current implementation? See two tasks here
* Make all specs green for JRuby and Rubinius
* Add JRuby and Rubinius to Travis

I launched current specs for JRuby and Rubinius. For Rubinius all are green. For JRuby all specs except one are green. Ready to fix this one red.

Thank you.

**Comment by alexdowad** [comment]
Thank you!
