### ISSUE TITLE
Beta-testers needed

### ISSUE THREAD

**Issue by alexdowad** [hamstergem/hamster#128]
Looking through GH's code search results, there are very few "serious" projects on GH using Hamster (almost none). It may be that there are closed-source projects out there which are using Hamster "in production". Certainly the number of gem downloads suggests that *someone* must be.

If some of those people can be found and encouraged to try out "edge" Hamster, their feedback will give us a lot more confidence that the library is solid. A tremendous number of changes (performance optimizations, etc) have been made since the 0.4.3 release. Although we have a very good test suite, I feel some more validation is necessary.

**Comment by alexdowad** [comment]
About 6 months has past. The `-rc3` version gem has been downloaded >1000 times. No bug reports against that version have come in. How much more time do you think we should give before shipping it?

**Comment by krainboltgreene** [comment]
I'm ready if you are.

**Comment by dubek** [comment]
I think it's ready.

**Comment by alexdowad** [comment]
I also think it's ready.

**Comment by krainboltgreene** [comment]
Alright, I'll release 1.0.0 tonight based on master.

**Comment by alexdowad** [comment]
@krainboltgreene, can you go ahead and cut the promised 1.0.0 gem?

**Comment by krainboltgreene** [comment]
Yep.

**Comment by krainboltgreene** [comment]
Done.

**Comment by alexdowad** [comment]
@harukizaemon @krainboltgreene @dubek @gcapizzi @ryantm @misfo @kef @cstorey @baconpat @gfredericks Thank you for your contributions toward this gem! Congrats to all on the 1.0 release!
