### ISSUE TITLE
Append Only behavior

### ISSUE THREAD

**Issue by krainboltgreene** [hamstergem/hamster#145]
I realized today that I wanted an append only dictionary. I couldn't find anything on the web so I think it's something we should discuss here:

Can we provide append-only behavior to any ruby collection data structure?

**Comment by alexdowad** [comment]
Is this still an issue we want to work on? If unsure, I suggest it can be triaged.

**Comment by krainboltgreene** [comment]
Unsure.

**Comment by alexdowad** [comment]
Closing for now, please re-open if anyone discovers this is really needed.
