### ISSUE TITLE
'atomic' gem is deprecated; use 'concurrent-ruby' instead

### ISSUE THREAD

**Issue by roryokane** [hamstergem/hamster#167]
I notice that [`hamster.gemspec` includes the `atomic` gem](https://github.com/hamstergem/hamster/blob/e32a799ca14223a99c47488822defdb5a189f1af/hamster.gemspec#L24):

```ruby
spec.add_runtime_dependency     "atomic", "~> 1.1"
```

The [`atomic` gem](https://rubygems.org/gems/atomic/) repository seems to be [github.com/ruby-concurrency/atomic](https://github.com/ruby-concurrency/atomic). Their README has this message:

> This gem has been deprecated in lieu of [Concurrent Ruby](http://www.concurrent-ruby.com/). This gem will be retained in GitHub and Rubygems.org indefinitely but no new development will occur, including updates to support new versions of Ruby, JRuby, and Java. All users of this gem are encouraged to update their projects to use `concurrent-ruby` instead.

So you may want to update your use of `atomic` to avoid potential incompatibilities with future Ruby versions.

[`atomic`’s README](https://github.com/ruby-concurrency/atomic#deprecated) shows that at least in some cases, it is as simple as renaming your use of `atomic` and `Atomic`:

> ```ruby
> # old way
> require 'atomic'
> my_atomic = Atomic.new(0)
> 
> # new way
> require 'concurrent'
> my_atomic = Concurrent::Atomic.new(0)
> ```

**Comment by alexdowad** [comment]
Hmm. Thanks for bringing this point up.

I hate to pull in the whole `concurrent` library, which is quite large, for this one teeny-tiny little thing. If you ever have a look at the implementation of `Atomic`, you will see it is positively trivial. But vendoring our own version of `Atomic` would also be a pain.

In our case, we use `Atomic` to make sure that each node of a lazy list will be only be realized once, on one thread. In some cases, the code which is used to realize a lazy list may have side effects, so this is important.

What do others think about this issue?

**Comment by roryokane** [comment]
You can `require 'concurrent/atomics'` to load only “atomic and thread synchronization classes”. The whole `concurrent` library will still have to be downloaded as a gem, but at least most of it won’t be loaded at runtime.

**Comment by dubek** [comment]
Another option is to have two implementations:

1. If the `concurrent` gem is installed, use it (`require 'concurrent/atomics'` and use the `Atomic` class).
2. Otherwise, build a naive (=slow) implementation using a Mutex for any read/write operation on @atomic (which can then be a normal fixnum).

This way hamster works out-of-the-box without other dependencies, and if you need List to be faster then you just `gem install concurrent`.

**Comment by krainboltgreene** [comment]
I'm pretty annoyed the decided to bundle it. Like, at the very least do it
the way Rails does.

**Comment by alexdowad** [comment]
So do we just bite the bullet and pull in `concurrent`? Or do we detect whether the user has already `require`d `concurrent`, and use it if it is already available?

**Comment by dubek** [comment]
I'm good with adding dependency on `concurrent` (instead of `atomic`), and in our code adding `require "concurrent/atomics"`.

**Comment by alexdowad** [comment]
If there are no other objections, shall we go ahead with @dubek's suggestion?

**Comment by dubek** [comment]
(It was @roryokane's suggestion, actually.)

**Comment by alexdowad** [comment]
Implemented @roryokane's suggestion in 25bda8c.

**Comment by dubek** [comment]
Nice.

BTW (not related to the concurrent gem): it might be clearer to extract those `if @atomic.get != 2` to something like:

```ruby
def head
  realize unless realized?
  @head
end

private

def realized?
  @atomic.get == 2
end
```

and so on for the other "states" of the `@atomic` var.

I might pursue it in a separate PR for review.

**Comment by alexdowad** [comment]
Sure, please do! Another option: instead of setting the atomic var to fixnums like 0, 1, or 2, use symbols. I'm pretty sure it will be just as fast (but a little benchmarking would be needed to confirm that).

**Comment by davejacobs** [comment]
Awesome! Do you plan to push this out to RubyGems soon?
