### ISSUE TITLE
Vector#assoc should return nil for malformed vectors.

### ISSUE THREAD

**Issue by xaviershay** [hamstergem/hamster#183]
```
irb(main):027:0> [[1, 2], nil].assoc(3)
=> nil
irb(main):028:0> Hamster.vector([1, 2], nil).assoc(3)
NoMethodError: undefined method `[]' for nil:NilClass
	from /Users/xavier/.gem/ruby/2.2.2/gems/hamster-1.0.0/lib/hamster/vector.rb:1143:in `block in assoc'
	from /Users/xavier/.gem/ruby/2.2.2/gems/hamster-1.0.0/lib/hamster/vector.rb:1205:in `each'
	from /Users/xavier/.gem/ruby/2.2.2/gems/hamster-1.0.0/lib/hamster/vector.rb:1205:in `traverse_depth_first'
	from /Users/xavier/.gem/ruby/2.2.2/gems/hamster-1.0.0/lib/hamster/vector.rb:405:in `each'
	from /Users/xavier/.gem/ruby/2.2.2/gems/hamster-1.0.0/lib/hamster/vector.rb:1143:in `assoc'
	from (irb):28
	from /Users/xavier/.rubies/cruby-2.2.2/bin/irb:11:in `<main>'
```

I plan to fix this, just filing here so I don't forget.

**Comment by alexdowad** [comment]
Hmm. Do we really want to fix this?

Your docs state: "Behaviour is undefined when elements do not meet assumptions (i.e. are not indexable collections)."

I'm happy to leave this as "undefined". Or if you think it's better to match `Array` more closely, that is also fine.

What MRI does: check whether each element is an `Array` (**or** is convertible to an `Array` using `#to_ary`), check whether it contains at least one item, and *only then* compare the items, using `#==`. Any elements which do not pass the first 2 checks are ignored.

The docs should probably specify that `#==` is used for comparison.

**Comment by xaviershay** [comment]
should stay as undefined, but a method missing error coming from inside the library is pretty gross. Makes it looks like a bug.

**Comment by alexdowad** [comment]
@xaviershay, please have a look at the following branch:

https://github.com/hamstergem/hamster/compare/vector_assoc_skips_bad_elements

Look good?

**Comment by xaviershay** [comment]
possibly want a spec for empty array, since you mention it in the commit message. Otherwise, LGTM!

**Comment by alexdowad** [comment]
I'd sooner let that fall under the umbrella of "undefined behavior". :)
