### ISSUE TITLE
Vector#transpose should raise TypeError on invalid types.

### ISSUE THREAD

**Issue by xaviershay** [hamstergem/hamster#185]
```
irb(main):054:0> [nil].transpose
TypeError: no implicit conversion of nil into Array
	from (irb):54:in `transpose'
	from (irb):54
	from /Users/xavier/.rubies/cruby-2.2.2/bin/irb:11:in `<main>'
irb(main):055:0> Hamster::Vector[nil].transpose
NoMethodError: undefined method `size' for nil:NilClass
	from /Users/xavier/.gem/ruby/2.2.2/gems/hamster-1.0.0/lib/hamster/vector.rb:1014:in `transpose'
	from (irb):55
	from /Users/xavier/.rubies/cruby-2.2.2/bin/irb:11:in `<main>'
```

**Comment by xaviershay** [comment]
Actual fix here is probably just calling `to_ary` on elements to match Ruby behaviour.

**Comment by alexdowad** [comment]
Sounds good. Can you come up with an example where `Array#transpose` works but `Vector#transpose` doesn't?

**Comment by xaviershay** [comment]
I think the implementation is correct, this is just to provide consistent exception types. So, pretty minor.

**Comment by alexdowad** [comment]
Looking at this again, I don't think that calling `#to_ary` on all the sub-vectors is really desirable. It will add performance cost for no real gain.

Have a look at this and see if you think it makes things better: https://github.com/alexdowad/hamster/commit/846b5889afbb19b396d811065f72adb08654c827

**Comment by xaviershay** [comment]
neat, kinda weird but I like it.
