### ISSUE TITLE
Untangle load-order dependencies between files

### ISSUE THREAD

**Issue by alexdowad** [hamstergem/hamster#196]
One design aim of Hamster is that users can load any subset of the library which they want to use. However, many of the files have dependencies on others. In some cases, there are _circular_ dependencies. This can lead to errors, depending on which files you load first.

To help untangle things, I have added a Rake task called `rake dependency_graph`. You have to have Graphviz installed to use it: `sudo apt-get install graphviz` on Ubuntu and Ubuntu-derived platforms. Here's what the graph looks like:

![depgraph](https://cloud.githubusercontent.com/assets/1067359/9326123/d64d75fc-4597-11e5-8373-57f2c75de174.gif)

What adjustments can we make so that the code is always loaded in a consistent order, regardless of which file you actually `require`?

Additionally, we need tests for this. Something like:

``` ruby
system("$:.unshift(HAMSTER_LIB_DIR); require 'hamster/vector'").should be_true
```

...But `HAMSTER_LIB_DIR` needs to be replaced by something that works.

**Comment by alexdowad** [comment]
Looking at the graph, I've also noticed that `hamster/version` is only `require`d from the main `hamster.rb` file. It should probably get pulled in by all of the individual structures as well.

**Comment by xaviershay** [comment]
I noticed last night `hamster/list` implicitly depends on `hamster/core_ext` (`.list` calls `.to_list`), that should be an easy one to break though.

**Comment by xaviershay** [comment]
I see two ways to solve the bulk of these:

* Features that would require another data-structure (e.g. `Set#sort` needs `SortedSet`) raise "feature not loaded" if the type they require is not present.
* Use monkey-patching to group cross-cutting features in a single file. You could fix the `nested` circular dependency by moving all the `to_ruby` definitions into it.

Probably a mix of the two is best.

Thoughts on those? Any other ideas?

**Comment by alexdowad** [comment]
Let me draw attention to another thing: `nested` pulls in *all* the collection classes. And almost all the collection classes pull in `nested`. So loading any one of them results in all the others getting pulled in as well.

Originally, it was possible to load the `Hamster` collections selectively. This is not true any more. Do we care?

What if the `nested` methods, like `Hamster.from`, were defined in `lib/hamster.rb`, and would only be available if the library was loaded with `require 'hamster'`, not if a specific collection was loaded with `require 'hamster/vector'` (for example)? Would that be better?

**Comment by alexdowad** [comment]
After discussion in another GH thread, `#to_ruby` was removed in 30a6aa8. Here is what the sourcefile dependency graph looks like now:

![depgraph](https://cloud.githubusercontent.com/assets/1067359/9793594/6c8d7c64-57e6-11e5-81e3-aba8d0002d6f.gif)
