### ISSUE TITLE
Remove List.enumerate?

### ISSUE THREAD

**Issue by alexdowad** [hamstergem/hamster#199]
Recently we have removed a couple of useless APIs. I'm eyeing `List.enumerate` for similar treatment...

Is there any reason to have this API method, given that we also have `Enumerable#to_list`?

The one thing `.enumerate` potentially has going for it is that it is lazy, and `#to_list` is not. Does that matter?

**Comment by xaviershay** [comment]
we need to have non-core extensions equivalents of all of our monkey-patches, so users can opt not to include core extensions.

**Comment by alexdowad** [comment]
Ah, OK. That makes sense.
