### ISSUE TITLE
can't find `master`'s `Hamster#from` and `Hamster#to_ruby` in any released gem version

### ISSUE THREAD

**Issue by Bill** [hamstergem/hamster#201]
I noticed the awesome `nested.rb` functionality on master. Then I improved it with a PR #200 to add support for converting `from` Ruby core `Struct`s.

Then I noticed that neither the `1.0.0` gem version I was using, nor any of the other released gem versions have `Hamster#from`.

Please publish an updated gem version.

**Comment by alexdowad** [comment]
I second this! We have also fixed several bugs since `1.0.0

**Comment by dubek** [comment]
:+1: for releasing `1.1.0` with the added functionality.

**Comment by dubek** [comment]
Who has the gem release button? @krainboltgreene ? Can you release a 1.1.0.pre.rc1 ?

**Comment by alexdowad** [comment]
Yes, it's @krainboltgreene. `1.1.0` gem, please!

**Comment by krainboltgreene** [comment]
I'll do it tonight!

On Mon, Oct 26, 2015 at 6:22 AM, Alex Dowad <notifications@github.com>
wrote:

> Yes, it's @krainboltgreene <https://github.com/krainboltgreene>. 1.1.0
> gem, please!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hamstergem/hamster/issues/201#issuecomment-151131400>.
>



-- 
Kurtis Rainbolt-Greene, Hacker
Software Developer
1631 8th St.
New Orleans, LA
70115

**Comment by Bill** [comment]
Did this happen?

**Comment by krainboltgreene** [comment]
Released as v2.0.0, since we had breaking public API changes (detailed in CHANGELOG.md)

**Comment by Bill** [comment]
goodun

**Comment by dubek** [comment]
So `Hamster.from` and `Hamster::Whatever#to_ruby` are available in the hamster 2.0.0 gem released yesterday.

Closing.
