### ISSUE TITLE
update_in() mutates original Ruby Hash

### ISSUE THREAD

**Issue by Bill** [hamstergem/hamster#206]
Creating a `Hamster::Hash` from a Ruby `Hash` and then using `update_in()` to modify a value in the hash, mutates the origianl Ruby `Hash`. See:

```
2.1.1 :002 > x = {name:'Pat'}
 => {:name=>"Pat"} 
2.1.1 :003 > Hamster.from(x).update_in(:name){|name| name << 'sy'}
 => Hamster::Hash[:name => "Patsy"] 
2.1.1 :004 > x
 => {:name=>"Patsy"} 
```

I expected `x` to remain unchanged.

I don't have a fix, but PR #207 has some specs that may help isolate the problem. I found this problem in version 2 but I also found that version 1 exhibits the same problem.

**Comment by alexdowad** [comment]
The problem is that you are storing a mutable object in `Hamster::Hash`, and using destructive (mutating) methods on it.

Use `name + 'sy'` instead and it will be fine.

**Comment by alexdowad** [comment]
The main GitHub page states about this:

> While Hamster collections are immutable, you can still mutate objects stored in them. We recommend that you don't do this, unless you are sure you know what you are doing.

**Comment by Bill** [comment]
d'oh. Thank you @alexdowad!!
