### ISSUE TITLE
Add Ruby 2.3-like methods

### ISSUE THREAD

**Issue by dubek** [hamstergem/hamster#212]
Ruby 2.3 adds some methods to Hash, Array and Enumerable: https://blog.blockscore.com/new-features-in-ruby-2-3/

We might want to imitate them (where applicable) in Hamster-compatible methods. This issue is meant as a general list + discussion area (I suggest adding each feature in its own commit / PR).

Here's a short list of the relevant new Ruby features mentioned in that post

* [x] `Array#dig`, `Hash#dig`
* [x] `Enumerable#grep_v`
* [x] `Hash#fetch_values`
* [x] Hash superset/subset `Hash#>` `Hash#<` etc.
* [x] `Hash#to_proc`

Note that we can implement these features regardless if we're running in Ruby 2.3.

**Comment by alexdowad** [comment]
+1

**Comment by dubek** [comment]
Added `Hash#fetch_values` in ed887846f89f56f444ca2107c628372fc83f0070

**Comment by dubek** [comment]
Added `Hash#to_proc` in 7433f92a0943d64c2dd367c4c597f8c7016dbc68

**Comment by dubek** [comment]
Thanks to @HParker who added `Hash#dig` in 500928ea887793960977a000ae9a937197e1cbc1

**Comment by dubek** [comment]
Hash `>=` `>` `<` `<=` added in 8a70322c1603f58d9c5c14c254ef49ac20f8e950

**Comment by alexdowad** [comment]
Thanks @dubek!

**Comment by dubek** [comment]
Thanks to @HParker who added `Vector#dig` in 42fb988cc08171231165679204de3ff120316cba
