### ISSUE TITLE
ruby-hamster now packaged for Debian / request: please add license to gem file

### ISSUE THREAD

**Issue by hzulla** [hamstergem/hamster#221]
Hi there,

ruby-hamster is being used by Sonic Pi to teach coding to kids. In an effort to bring Sonic Pi to Debian, the hamster gem has now been packaged: [ruby-hamster at Debian](https://packages.debian.org/sid/ruby-hamster).

While packaging, [one issue turned up](https://lists.debian.org/debian-ruby/2016/01/msg00089.html) - what is the correct license for this gem, since there is no license file in the gem download package?

For unknown reasons, the license file is present in the github repo, but not in the gem file. To make packaging and distribution easier, please consider adding the license file to the gem download. Thanks!

**Comment by alexdowad** [comment]
@hzulla Thanks for your interest in Hamster. I have adjusted the gemspec to include the license file in the gem.

@krainboltgreene New minor version?

**Comment by krainboltgreene** [comment]
:+1:

**Comment by alexdowad** [comment]
@krainboltgreene There is a funny build failure whereby Travis CI can't install the Hamster gem on certain Ruby versions. I am looking at it.

**Comment by krainboltgreene** [comment]
Weeeeeee. Thanks for checking on it.

**Comment by alexdowad** [comment]
Looks like Travis CI is using an old version of Bundler. From their output:

```
$ bundle --version
Bundler version 1.8.4
```

On my PC:

```
21:42 ~prog/Ruby/parser % rbenv shell 2.3.0
21:42 ~prog/Ruby/parser % bundle --version
Bundler version 1.11.2
```

In [this thread](https://github.com/bundler/bundler/issues/3560), one of the Bundler devs stated that he thinks this bug should be fixed by a commit which made it into v1.11.2.

**Comment by hzulla** [comment]
Thanks!

A new release would be helpful, as the current version 2.0.0 doesn't work with ruby-concurrent 1.0.0 and [needed to be patched](http://anonscm.debian.org/cgit/pkg-ruby-extras/ruby-hamster.git/tree/debian/patches/02-concurrent-ruby.patch?h=debian/2.0.0-2) for Debian.

**Comment by alexdowad** [comment]
@hzulla Why not just submit a PR rather than patching the code downstream?

**Comment by hzulla** [comment]
@alexdowad the Patch for Debian was taken from your current development version.

@Ch4s3 patched this already [here](https://github.com/hamstergem/hamster/commit/74e89448d2c9051082547e1ae62e6b03f41623ce).

**Comment by alexdowad** [comment]
@krainboltgreene Can you go ahead and cut a new minor release? It looks like the Travis CI failure is a problem on their side.

**Comment by hzulla** [comment]
So, new release coming?

**Comment by alexdowad** [comment]
@krainboltgreene New gem please!

**Comment by krainboltgreene** [comment]
Out!

**Comment by krainboltgreene** [comment]
@alexdowad It was a major release, actually, since we changed the behavior of values_at.

**Comment by Ch4s3** [comment]
Awesome! @hzulla I'm excited to see that the new version is used on Sonic Pi!

**Comment by samaaron** [comment]
Hamster is wicked. Thanks so much for creating it. Immutability is such an important thing!
