### ISSUE TITLE
The default branch when viewing the repo is `breaking-up-add-spec`, which is 2 years old

### ISSUE THREAD

**Issue by roryokane** [hamstergem/hamster#222]
When I visit this repo on GitHub at https://github.com/hamstergem/hamster, the default branch shown is the first branch on the list, [`breaking-up-add-spec`](https://github.com/hamstergem/hamster/tree/breaking-up-add-spec). The message at the top right of the file tree is “Latest commit 2682160 on Dec 18, 2013”, and all the files say they were updated “2 years ago”, which makes the project look abandoned.

The default visible branch should be `master`, which is viewable at https://github.com/hamstergem/hamster/tree/master, and shows a more reasonable “Latest commit 0cffcf3 3 days ago”. An admin of this repo can make `master` the default by visiting [this repo’s Settings → Branches](https://github.com/hamstergem/hamster/settings/branches) and changing the “Default branch”.

**Comment by alexdowad** [comment]
Done. Thank you for pointing this out.

**Comment by Staff457** [comment]
**Cast a Love spells, marriage spells, breakup spells & bring back lost love spells. Witchcraft love spells, voodoo love spells, black magic love spells, binding love spells, marriage love spells, white magic love spells, divorce spells, spells for lost love, love spells that work fast, love spells for men, love spells for women, love potions, love muti, love rings, witchcraft spells, wiccan love spells, wicca love spells, traditional healing, divination & voodoo magic for love, email Dr Olorun Agbalazzy now: Olorunoduduwaspiritualtemple@gmail.com**
