### ISSUE TITLE
Recursive data structures

### ISSUE THREAD

**Issue by guncha** [hamstergem/hamster#231]
I'm wondering what your thoughts are about this kind of thing. I tried to create a recursive data structure:

```ruby
n1 = {}
n2 = {child: n1}
n1[:parent] = n2
n1.inspect # => "{:child=>{:parent=>{...}}}"
Hamster.from(n1)
# SystemStackError: stack level too deep
# from /Users/gunca/.rvm/gems/ruby-2.2.3/gems/hamster-3.0.0/lib/hamster/nested.rb:27:in `each'
```

I want to use persistent data structures to represent an AST, but cycles like this are unfortunately very common.

**Comment by alexdowad** [comment]
Persistent data structures cannot be used in this way. Sorry. It's by design.

**Comment by dubek** [comment]
@guncha If your AST is really a tree, then it shouldn't have cycles... :-)
