### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by lcampbell-zendesk** [hamstergem/hamster#236]
I saw build failing, deps out of date and most changes a year ago. Should there be a depreciation/unmaintained warning in the readme? Or is it just that the library is done and no further work needs doing?

**Comment by alexdowad** [comment]
Thanks for the question. As far as I am concerned, the library is finished.
Any performance improvements would be welcome but I will not be the one to
make them.

If you or anyone else wants to submit a PR to update the dependencies, that
would be very welcome.

As far as the broken build, I think Travis used to work well for us, but
later we started to see so many spurious failures that we tired of even
bothering to look into them.

I think if you clone the repo and run the tests locally, you will see that
they all pass. If not, tell me and I will fix them.
