### ISSUE TITLE
Use Adamanitum to freeze stuff

### ISSUE THREAD

**Issue by sporkmonger** [hamstergem/hamster#63]
For subclasses of Hamster objects, it would be incredibly useful to have memoization capabilities that didn't freak out about the fact that the objects are frozen. The Adamantium gem gives you that ability. (In my specific case, I want to be able to track the mean/median/mode/etc for vectors without having performance go to shit from recalculating all that from the 10 different places that require these values.)

**Comment by alexdowad** [comment]
Triaging this issue, please re-open if there is more to say.
